typography_spectrum: 0.7349800875363913
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.10593210608827619
  lightness: 0.8035416442349179
  saturation: 0.6198153380025018
  rhythmicContrast: 0.5884019671280574
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.4578623504844711
author:
  name: 'Jörg Hoheisel '
  url: ''
  email: ''
name: 'Hoheisel '
navigation:
  - name: LinkedIn Profile
    id: 79e72727-c41d-406a-9ef8-ab9f11ecba16
    type: content
title: Jörg Hoheisel
description: Interaction and User Experience Designer for web
